# site data
name: Marvin Anderson's Portfolio
url: https://mlan225.github.io
baseurl: /portfolio
email: mlanderson225@gmail.com
linkedin: https://www.linkedin.com/in/marvin-anderson/
github: https://github.com/mlan225
resume: /assets/img/MarvinAnderson_resume.pdf